version: '3.7'
services: 
    db:
        image: postgres:10
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=sardor
            - POSTGRES_PASSWORD=123
            - POSTGRES_DB=db