###--------------CUSTOMERS-------------------###

### Customer Registration
POST http://127.0.0.1:9999/api/customers  HTTP/1.1
Content-Type: application/json

{
    "name": "masha",
    "phone": "+998941112233",
    "password": "123456"
}

### Token generation
POST http://127.0.0.1:9999/api/customers/token  HTTP/1.1
Content-Type: application/json

{
    "login": "+998941112233",
    "password": "123456"
}

### Get all active products
GET http://127.0.0.1:9999/api/customers/products  HTTP/1.1

### Get active purchases
GET http://127.0.0.1:9999/api/customers/purchases  HTTP/1.1




###-----------------MANAGERS-----------------------###

### First Create Token if Manager Exists
POST http://127.0.0.1:9999/api/managers/token  HTTP/1.1
Authorization:<token>
Content-Type: application/json

{
    "phone": "+992000000001",
    "password": "secret"
}


### Registration
POST http://127.0.0.1:9999/api/managers  HTTP/1.1
Authorization:<token>
Content-Type: application/json

{
    "id": 0,
    "name": "Katya",
    "phone": "+992000000002",
    "roles": ["MANAGER", "ADMIN"]
}

### Registration
POST http://127.0.0.1:9999/api/managers  HTTP/1.1
Authorization:<token>
Content-Type: application/json

{
    "id": 0,
    "name": "Petya",
    "phone": "+992000000003",
    "roles": ["MANAGER"]
}



### Make Sale
POST http://127.0.0.1:9999/api/managers/sales  HTTP/1.1
Authorization:<token>
Content-Type: application/json

{
    "id": 0,
    "customer_id": "null",
    "positions": [
        {"id": 0, "product_id": 1, "qty": 2, "price": 500},
        {"id": 0, "product_id": 2, "qty": 1, "price": 1000},
    ]
}

### GET Sales
GET http://127.0.0.1:9999/api/managers/sales  HTTP/1.1


###
GET http://127.0.0.1:9999/api/managers/products  HTTP/1.1


###
POST http://127.0.0.1:9999/api/managers/products  HTTP/1.1
Authorization:<token>
Content-Type: application/json

{
    "id": 0,
    "name": "iPhone",
    "qty": 2,
    "price": 500000
}

###
DELETE http://127.0.0.1:9999/api/managers/products/1  HTTP/1.1
Authorization:<token>
Content-Type: application/json


###
GET http://127.0.0.1:9999/api/managers/customers HTTP/1.1


###
POST http://127.0.0.1:9999/api/managers/customers HTTP/1.1
Authorization:<token>
Content-Type: application/json

###
DELETE http://127.0.0.1:9999/api/managers/customers/1 HTTP/1.1
Authorization:<token>
Content-Type: application/json